const $ = (id) => document.getElementById(id);
const storageKey = 'follow-prompter-v1';
const defaultSettings = { fontSize: 52, lineHeight: 1.65, speed: 18, mirror: true, mode: 'hybrid' };
let state = { title: '', text: '', settings: defaultSettings, activeIndex: 0, playing: false, listening: false };
let animationFrame, lastFrame, hideTimer, wakeLock;
let transcriberWorker, mediaStream, audioContext, mediaSource, processorNode;
let audioChunks = [], bufferedSamples = 0, modelReady = false, modelLoading = false, processingChunk = false;

function load() { try { state = { ...state, ...JSON.parse(localStorage.getItem(storageKey)) }; state.settings = { ...defaultSettings, ...state.settings }; } catch {} }
function save() { localStorage.setItem(storageKey, JSON.stringify({ title: state.title, text: state.text, settings: state.settings })); $('saveHint').textContent = '已自动保存'; setTimeout(() => $('saveHint').textContent = '稿件会自动保存在这台 iPad 上', 1400); }
function paragraphs() { return state.text.split(/\n\s*\n|\n/).map(s => s.trim()).filter(Boolean); }
function applyEditor() { $('scriptTitle').value = state.title; $('scriptText').value = state.text; }
function applySettings() { const s = state.settings; $('mirrorSwitch').checked = s.mirror; $('fontSize').value=s.fontSize; $('lineHeight').value=s.lineHeight; $('scrollSpeed').value=s.speed; $('followMode').value=s.mode; $('fontSizeOutput').value=`${s.fontSize}px`; $('lineHeightOutput').value=s.lineHeight; $('speedOutput').value=`${s.speed}`; $('scriptStage').style.fontSize=`${s.fontSize}px`; $('scriptStage').style.lineHeight=s.lineHeight; $('scriptStage').classList.toggle('mirrored', s.mirror); }
function renderScript() { const list = paragraphs(); $('scriptStage').replaceChildren(...list.map((text, index) => { const p=document.createElement('p'); p.className='paragraph'; p.dataset.index=index; p.textContent=text; return p; })); state.activeIndex=Math.min(state.activeIndex, Math.max(0,list.length-1)); markActive(); }
function markActive() { document.querySelectorAll('.paragraph').forEach((p,i)=>p.className=`paragraph ${i === state.activeIndex ? 'active' : i < state.activeIndex ? 'past' : ''}`); }
function goTo(index, smooth=true) { const list=paragraphs(); if (!list.length) return; state.activeIndex=Math.max(0,Math.min(index,list.length-1)); markActive(); const item=document.querySelector(`.paragraph[data-index="${state.activeIndex}"]`); item?.scrollIntoView({block:'center', behavior:smooth?'smooth':'auto'}); }
function setStatus(text) { $('statusPill').textContent=text; }
function togglePlay() { state.playing=!state.playing; $('toggleScroll').textContent=state.playing?'❚❚':'▶'; $('toggleScroll').setAttribute('aria-label',state.playing?'暂停自动滚动':'开始自动滚动'); if(state.playing){ lastFrame=performance.now(); animationFrame=requestAnimationFrame(scrollLoop); setStatus('匀速滚动中'); } else { cancelAnimationFrame(animationFrame); setStatus(state.listening?'正在语音跟随':'已暂停'); } }
function scrollLoop(now) { if(!state.playing) return; const delta=(now-lastFrame)/1000; lastFrame=now; const box=$('teleprompter'); box.scrollTop+=state.settings.speed*delta; const elems=[...document.querySelectorAll('.paragraph')]; const center=window.innerHeight/2; const nearest=elems.reduce((best,p,i)=>Math.abs(p.getBoundingClientRect().top-center)<Math.abs(elems[best].getBoundingClientRect().top-center)?i:best, state.activeIndex); if(nearest!==state.activeIndex){state.activeIndex=nearest;markActive();} animationFrame=requestAnimationFrame(scrollLoop); }
function normalize(value) { return value.toLowerCase().replace(/[，。！？、；：“”‘’（）\s,.!?;:]/g,''); }
function findBestMatch(spoken) { const words=normalize(spoken); if(words.length<3) return -1; const list=paragraphs(); let best=-1, bestScore=0; list.forEach((p,i)=>{ const target=normalize(p); let score=0; for(let len=Math.min(10,words.length);len>=3;len--){ for(let at=0;at<=words.length-len;at++){ if(target.includes(words.slice(at,at+len))){score=Math.max(score,len/Math.min(16,target.length)); break;} } } if(score>bestScore){bestScore=score;best=i;} }); return bestScore>=.19?best:-1; }
function initWorker() {
  if (transcriberWorker) return;
  transcriberWorker = new Worker('./transcription-worker.js', { type: 'module' });
  transcriberWorker.onerror = () => { modelLoading=false; setStatus('本地模型需要从 HTTPS 网页启动'); stopListening(); };
  transcriberWorker.onmessage = ({ data }) => {
    if (data.type === 'progress') { setStatus(data.message); resetHideTimer(); }
    if (data.type === 'ready') { const shouldStart=modelLoading; modelLoading=false; modelReady=true; if(shouldStart) { setStatus('模型准备完成，正在打开麦克风…'); startMicrophone(); } }
    if (data.type === 'result') { processingChunk=false; const hit=findBestMatch(data.text); if(hit>=0) { goTo(hit); setStatus(`已跟随到第 ${hit+1} 段`); } else setStatus(data.text ? '没有匹配到稿件，请继续说' : '没有听清，请靠近麦克风再试'); resetHideTimer(); sendBufferedAudio(); }
    if (data.type === 'error') { modelLoading=false; processingChunk=false; setStatus(`本地模型无法启动：${data.message}`); stopListening(); }
  };
}
function resample(input, fromRate, toRate=16000) { if(fromRate===toRate) return input; const length=Math.round(input.length*toRate/fromRate); const output=new Float32Array(length); const ratio=fromRate/toRate; for(let i=0;i<length;i++){ const start=Math.floor(i*ratio), end=Math.min(input.length,Math.floor((i+1)*ratio)); let sum=0; for(let j=start;j<Math.max(start+1,end);j++)sum+=input[j]||0; output[i]=sum/Math.max(1,end-start); } return output; }
function addAudio(data) { audioChunks.push(data); bufferedSamples+=data.length; const maxSamples=audioContext.sampleRate*18; while(bufferedSamples>maxSamples && audioChunks.length){bufferedSamples-=audioChunks.shift().length;} sendBufferedAudio(); }
function sendBufferedAudio() { if(!state.listening||!modelReady||processingChunk||bufferedSamples<audioContext.sampleRate*2.5) return; const take=Math.min(bufferedSamples, audioContext.sampleRate*3); const raw=new Float32Array(take); let at=0; while(at<take&&audioChunks.length){ const first=audioChunks[0], use=Math.min(first.length,take-at); raw.set(first.subarray(0,use),at); at+=use; if(use===first.length)audioChunks.shift();else audioChunks[0]=first.subarray(use); } bufferedSamples-=take; processingChunk=true; const audio=resample(raw,audioContext.sampleRate); transcriberWorker.postMessage({type:'transcribe',audio},[audio.buffer]); }
async function startMicrophone() { try { mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}); audioContext=new (window.AudioContext||window.webkitAudioContext)(); await audioContext.resume(); mediaSource=audioContext.createMediaStreamSource(mediaStream); processorNode=audioContext.createScriptProcessor(4096,1,1); processorNode.onaudioprocess=e=>addAudio(new Float32Array(e.inputBuffer.getChannelData(0))); mediaSource.connect(processorNode); processorNode.connect(audioContext.destination); state.listening=true; $('toggleListening').classList.add('listening'); $('toggleListening').textContent='■'; setStatus('正在本地聆听…'); resetHideTimer(); } catch(e) { setStatus('请允许麦克风权限，并从 HTTPS 网页打开'); stopListening(); } }
function stopListening() { state.listening=false; processingChunk=false; audioChunks=[]; bufferedSamples=0; processorNode?.disconnect(); mediaSource?.disconnect(); mediaStream?.getTracks().forEach(track=>track.stop()); audioContext?.close(); processorNode=mediaSource=mediaStream=audioContext=undefined; $('toggleListening').classList.remove('listening'); $('toggleListening').textContent='🎙'; if(!state.playing)setStatus('准备就绪'); }
function toggleListening() { if(state.listening||modelLoading){ if(modelLoading){modelLoading=false; setStatus('已取消模型下载');} stopListening(); return; } if(location.protocol==='file:'){setStatus('本地文件不能启动 AI；请从 HTTPS 地址打开');return;} if(!navigator.mediaDevices?.getUserMedia){setStatus('请从 HTTPS 网页打开，才能使用麦克风');return;} initWorker(); if(modelReady){startMicrophone();return;} modelLoading=true; setStatus('正在下载本地中文模型…'); transcriberWorker.postMessage({type:'load'}); }
async function keepAwake() { try { wakeLock=await navigator.wakeLock?.request('screen'); } catch {} }
function showPrompter() { state.title=$('scriptTitle').value.trim(); state.text=$('scriptText').value.trim(); save(); if(!state.text){ $('scriptText').focus(); $('saveHint').textContent='请先输入一段口播稿'; return; } $('editorView').classList.add('hidden'); $('prompterView').classList.remove('hidden'); renderScript(); applySettings(); goTo(0,false); keepAwake(); if(state.settings.mode!=='voice'&&!state.playing) togglePlay(); if(state.settings.mode==='voice') setStatus('仅 AI 跟读：点击麦克风开始'); }
function exitPrompter() { if(state.playing)togglePlay(); stopListening(); wakeLock?.release(); $('prompterView').classList.add('hidden'); $('editorView').classList.remove('hidden'); }
function resetHideTimer(){ $('controls').classList.remove('dim');$('statusPill').classList.remove('dim');clearTimeout(hideTimer); if(!state.listening&&!modelLoading)hideTimer=setTimeout(()=>{$('controls').classList.add('dim');$('statusPill').classList.add('dim');},3500); }

load(); applyEditor(); applySettings();
$('scriptTitle').addEventListener('input',()=>{state.title=$('scriptTitle').value;save()}); $('scriptText').addEventListener('input',()=>{state.text=$('scriptText').value;save()});
$('startPrompter').onclick=showPrompter; $('exitPrompter').onclick=exitPrompter; $('toggleScroll').onclick=togglePlay; $('toggleListening').onclick=toggleListening; $('previousParagraph').onclick=()=>goTo(state.activeIndex-1); $('nextParagraph').onclick=()=>goTo(state.activeIndex+1); $('tapLeft').onclick=()=>goTo(state.activeIndex-1); $('tapRight').onclick=()=>goTo(state.activeIndex+1);
$('openSettings').onclick=()=>$('settingsDialog').showModal(); ['mirrorSwitch','fontSize','lineHeight','scrollSpeed','followMode'].forEach(id=>$(id).addEventListener('input',()=>{state.settings={mirror:$('mirrorSwitch').checked,fontSize:+$('fontSize').value,lineHeight:+$('lineHeight').value,speed:+$('scrollSpeed').value,mode:$('followMode').value}; applySettings();save();}));
document.addEventListener('pointerdown',resetHideTimer); document.addEventListener('keydown',(e)=>{if(e.key==='Escape'&&!$('prompterView').classList.contains('hidden'))exitPrompter(); if(e.key===' '&&!$('prompterView').classList.contains('hidden')){e.preventDefault();togglePlay();}}); resetHideTimer();
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
